ARG RUBY_VERSION=3.4.10
FROM ghcr.io/rails/devcontainer/images/ruby:${RUBY_VERSION}
ARG RUBY_VERSION

ENV PATH="/home/vscode/.local/bin:/home/vscode/.local/share/mise/installs/ruby/${RUBY_VERSION}/bin:${PATH}"
ENV BINDING="0.0.0.0"